# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true        

    - name: Build
      run: |
        mkdir ..\tmp
        go build -o ../tmp/ -v ./...
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: terraform-provider-netapp-cloudmanager
        path: D:\a\custom-netapp-terraform-provider\tmp\terraform-provider-netapp-cloudmanager.exe
